version: "3"

services:
  graph_db:
    image: arangodb
    restart: unless-stopped
    ports:
      - 8529:8529
    environment:
      ARANGO_ROOT_PASSWORD: secret
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps
  rel_db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gagm
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gagm
    ports:
      - 5432:5432
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
  backend:
    build: ./backend
    cpus: 4
    ports:
      - 8000:8000
    environment:
      WORKERS: 2
      APP_PORT: 8000
      APP_DEBUG: false
      GRAPH_DB_HOST: graph_db
      GRAPH_DB_PORT: 8529
      GRAPH_DB_USER: root
      GRAPH_DB_PASS: secret
      REL_DB_HOST: rel_db
      REL_DB_PORT: 5432
      REL_DB_USER: gagm
      REL_DB_PASS: password
      FRONTEND_SECRET: secret_key
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    stop_signal: SIGTERM
    depends_on:
      - rel_db
      - graph_db
    # volumes:
    #   - ./app/models:/opt/app/models
  frontend:
    build: ./frontend
    environment:
      APP_PORT: 5000
      BACKEND_IP: backend
      BACKEND_PORT: 8000
      BACKEND_KEY: secret_key
      REL_DB_HOST: rel_db
      REL_DB_PORT: 5432
      REL_DB_USER: gagm
      REL_DB_PASS: password
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - backend
      - rel_db
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
  postgres-data:
